#!/usr/bin/env bash
# Concatenate modular stylesheets into mor_website_dioxus_ui/src/editor_ui.css.
# Can be run from any directory.
set -euo pipefail

# 1. Dynamically find the workspace root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_ROOT="$( dirname "$SCRIPT_DIR" )"

# 2. Use absolute paths based on the new UI crate location
SRC_DIR="$WORKSPACE_ROOT/mor_website_dioxus_ui/assets/css/editor_styles"
OUT="$WORKSPACE_ROOT/mor_website_dioxus_ui/assets/css/editor_ui.css"

if [ ! -d "$SRC_DIR" ]; then
    echo "error: $SRC_DIR not found" >&2
    exit 1
fi

{
    echo "/* AUTO-GENERATED by build_editor_styles.sh from mor_website_dioxus_ui/assets/css/editor_styles/*.css"
    echo "   Do NOT edit this file by hand. Edit the modular sources and re-run the script. */"
    echo ""
    # Sort by filename so the numeric prefix controls cascade order.
    find "$SRC_DIR" -maxdepth 1 -name '*.css' | LC_ALL=C sort | while read -r f; do
        echo ""
        echo "/* ============================================================"
        echo "   $(basename "$f")"
        echo "   ============================================================ */"
        cat "$f"
        echo ""
    done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines from $(find "$SRC_DIR" -maxdepth 1 -name '*.css' | wc -l) sources)"