[package]
name = "mor_website_core"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
log.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit = "0.25"
zip.workspace = true

roxmltree.workspace = true
base64 = "0.22"
directories = "5"
tokio = { version = "1", features = ["time"] }

# Binary/Compressed Rehydration
postcard = { version = "1.0", features = ["alloc"] }
zstd = "0.13"